version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: shipment-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shipment_db
      MYSQL_USER: shipment_user
      MYSQL_PASSWORD: shipment_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./data.sql:/docker-entrypoint-initdb.d/2-data.sql

volumes:
  mysql_data:
